repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        verbose: true
      - id: end-of-file-fixer
        verbose: true
      - id: check-yaml
        verbose: true
      - id: check-added-large-files
        verbose: true
      - id: check-json
        verbose: true
      - id: check-toml
        verbose: true
      - id: check-merge-conflict
        verbose: true
      - id: detect-private-key
        verbose: true

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.7
    hooks:

      - id: ruff-check
        exclude: '.*/tests/.*'
        args: [ --fix, --show-fixes ]
        verbose: true

      - id: ruff-format
        args: [ --diff, --check]
        verbose: true

      - id: ruff-format
        verbose: true
