"""create account table

Revision ID: 27221c576d96
Revises: a1284021bd42
Create Date: 2026-01-24 17:45:18.533726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27221c576d96'
down_revision: Union[str, Sequence[str], None] = 'a1284021bd42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column(
        "created_at",
        sa.DateTime(timezone=True),
        server_default=sa.func.now(),
        nullable=False,
    ),
    sa.Column(
        "updated_at",
        sa.DateTime(timezone=True),
        server_default=sa.func.now(),
        nullable=False,
    ),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),

    sa.UniqueConstraint('user_id', 'name', name='uq_account_user_id_name')
    )
    # ### end Alembic commands ###

    # Create a trigger function to auto-update updated_at


    # Attach the trigger to the users table
    op.execute("""
               CREATE TRIGGER update_accounts_updated_at
               BEFORE UPDATE
               ON accounts
               FOR EACH ROW
               EXECUTE FUNCTION update_updated_at_column();
   """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS update_accounts_updated_at ON accounts")

    op.drop_constraint('uq_account_user_id_name', 'accounts', type_='unique')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts')
    # ### end Alembic commands ###
