"""fix account table

Revision ID: 9d652c3c857a
Revises: 79e6ebcfa450
Create Date: 2026-01-15 17:29:09.392891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9d652c3c857a'
down_revision: Union[str, Sequence[str], None] = '79e6ebcfa450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Apply schema changes to the accounts table for migration revision 9d652c3c857a.
    
    - Change `created_at` and `updated_at` to timezone-aware DateTime and set a server default of the current timestamp.
    - Remove the existing unique constraint on `name`.
    - Add a non-unique index on `user_id`.
    - Add a new unique constraint on the composite (`user_id`, `name`).
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.func.now(),
               existing_nullable=False)
    op.alter_column('accounts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               server_default=sa.func.now(),
               existing_nullable=False)
    op.drop_constraint(op.f('accounts_name_key'), 'accounts', type_='unique')
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_unique_constraint('uq_account_user_id_name', 'accounts', ['user_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_account_user_id_name', 'accounts', type_='unique')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.create_unique_constraint(op.f('accounts_name_key'), 'accounts', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('accounts', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('accounts', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###