"""add family expire field

Revision ID: a1284021bd42
Revises: be0f07ef0f89
Create Date: 2026-01-24 17:42:00.420736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1284021bd42'
down_revision: Union[str, Sequence[str], None] = 'be0f07ef0f89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('family_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

    op.execute(
        "UPDATE refresh_tokens SET family_expires_at = expires_at"
    )

    op.alter_column(
        'refresh_tokens',
        'family_expires_at',
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'family_expires_at')
    # ### end Alembic commands ###
